import createClient, { ClientMethod, Middleware } from 'openapi-fetch';
import type { paths } from '../../open-api/schema'; // generated by openapi-typescript
import { Injectable } from '@angular/core';
import { TokenService } from 'packages/shared/src/lib/services/token.service';
import { environment } from '../../environments/environment';

@Injectable({
  providedIn: 'root',
})
export class OpenApiService {
  readonly client = createClient<paths>({
    baseUrl: environment.apiUrl + '/v1/',
  });

  get authorizationHeader(): string | undefined {
    const token = this.tokenService.token;

    if (!token) {
      return undefined;
    }

    return 'Bearer ' + [token.userId, token.deviceId, token.token].join('_');
  }

  constructor(private tokenService: TokenService) {}
}
